save_dir: workspace/shuffle_pan_yolox_s
model:
  num_classes: 80
  backbone:
    name: shufflenet_v2_x0_5
    pretrained: True
  neck:
    name: pan
    out_channels: 96
  head:
    inner_channel: 96
    stacks: 2
    conf_thresh: 0.1
    nms_thresh: 0.6
    center_radius: 2.5
    reg_weights: 5.0
    iou_type: iou
    class_agnostic: False
data:
  size: 416
  train_img_dir: /data/liangheming/coco/train2017
  train_json_path: /data/liangheming/coco/annotations/instances_train2017.json
  val_img_dir: /data/liangheming/coco/val2017
  val_json_path: /data/liangheming/coco/annotations/instances_val2017.json

device:
  batchsize_per_gpu: 64
  workers_per_gpu: 4
  gpus: [0,1]

optim:
  epochs: 300
  no_aug_epoch: 15
  lr: 0.014
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epoch: 1